"""Run Python code generated by AI agents.

SECURITY: Uses exec() intentionally. Runs inside Docker container (approved design).
"""

import json
import signal
import traceback
from typing import Any

import numpy
import pandas


def run_generated_code(
    code: str,
    data_context: dict[str, Any],
    timeout_seconds: int = 30,
) -> dict[str, Any]:
    """Run generated Python code and capture its JSON output.

    Code must set 'output' variable to a JSON string.
    """
    namespace = {
        "pd": pandas,
        "pandas": pandas,
        "np": numpy,
        "numpy": numpy,
        "json": json,
        "data_context": data_context,
        "output": None,
    }

    def timeout_handler(signum, frame):
        raise TimeoutError(f"Code timed out after {timeout_seconds}s")

    previous_handler = signal.signal(signal.SIGALRM, timeout_handler)
    signal.alarm(timeout_seconds)

    try:
        compiled = compile(code, "<agent-generated>", "exec")
        exec(compiled, namespace)  # noqa: S102
        signal.alarm(0)

        raw_output = namespace.get("output")
        if raw_output is None:
            return {
                "success": False,
                "output": None,
                "error": "No 'output' variable set",
                "generated_code": code,
            }

        parsed = json.loads(raw_output) if isinstance(raw_output, str) else raw_output
        return {
            "success": True,
            "output": parsed,
            "error": None,
            "generated_code": code,
        }

    except (TimeoutError, Exception) as err:
        signal.alarm(0)
        error_message = (
            str(err) if isinstance(err, TimeoutError) else traceback.format_exc()
        )
        return {
            "success": False,
            "output": None,
            "error": error_message,
            "generated_code": code,
        }
    finally:
        signal.signal(signal.SIGALRM, previous_handler)
